// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OyunDukkani.Data;

#nullable disable

namespace OyunDukkani.Data.Migrations
{
    [DbContext(typeof(OyunlarContext))]
    partial class OyunlarContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("OyunDukkani.Data.Oyunlar", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BarkodNumarasi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Fiyati")
                        .HasColumnType("float");

                    b.Property<string>("OyunAdi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Platformu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TekPlatform")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("oyunlar");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BarkodNumarasi = "1234567890123",
                            Fiyati = 59.990000000000002,
                            OyunAdi = "The Witcher 3",
                            Platformu = "PC",
                            TekPlatform = true
                        },
                        new
                        {
                            Id = 2,
                            BarkodNumarasi = "9876543210123",
                            Fiyati = 39.990000000000002,
                            OyunAdi = "Grand Theft Auto V",
                            Platformu = "PlayStation 4",
                            TekPlatform = false
                        },
                        new
                        {
                            Id = 3,
                            BarkodNumarasi = "4567890123456",
                            Fiyati = 49.990000000000002,
                            OyunAdi = "The Legend of Zelda: Breath of the Wild",
                            Platformu = "Nintendo Switch",
                            TekPlatform = true
                        },
                        new
                        {
                            Id = 4,
                            BarkodNumarasi = "7890123456789",
                            Fiyati = 44.990000000000002,
                            OyunAdi = "Red Dead Redemption 2",
                            Platformu = "Xbox One",
                            TekPlatform = false
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
